### PR TITLE
Add instructions for installing babel es2015 and es2016 presets

### PR DESCRIPTION
**Pull request by codyjlandstrom**

### CODE REVIEW

**Comment by Jeremboo** [comment]
Thx for your request ☺.  My repo cannot be work without with packages for you ?

 You could also added this dependencies intro 'packages.json'

**Comment by codyjlandstrom** [comment]
Ah yes! My bad, I should have added these to packages.json.
For some reason it's requiring a Babel Preset for es2015 and es2016, so I think the issue is with my setup. This is the error that is printing:
`Compiling of node_modules/auto-reload-brunch/vendor/auto-reload.js failed. Couldn't find preset "[project-path]/node_modules/babel-preset-es2015" relative to directory "node_modules/auto-reload-brunch/vendor"`

**Comment by Jeremboo** [comment]
Hum... The `auto-reload-brunch` dependencies do not seem to be automatically installed for you. Maybe checks your node.js version !

**Comment by codyjlandstrom** [comment]
Good call!
I was running v4.5.0 LTS... Upgraded to v6.5.0 and all works fine. Thanks for the help.

**Comment by Jeremboo** [comment]
Good ! I had the same problem with dependencies :)

**Pull request closed without merging**
